[package]
name = "day-3"
version = "0.1.0"
authors = ["Benoît Faucon <benoit.faucon@mindsay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
